### PR TITLE
updated buttons stylings like padding  and border-radius.

### PR DESCRIPTION
**Pull request by Shivakumarjagadam**
## Description

[Please include a brief description of the changes or features added]
 

I was improved the button stylings in the saved documents section. Specifically, I made the following changes:

1. Padding: I increased the padding around the buttons to ensure they are more touch-friendly and visually appealing. This change provides a more comfortable and accessible user experience by making the buttons easier to tap or click.

2. Border-Radius: I adjusted the border-radius of the buttons to give them a more modern and sleek appearance. Rounded corners help soften the overall look, making the interface feel more inviting and less harsh.

3. Space-Around: I utilized the space-around property to evenly distribute the space around the buttons. This ensures that the buttons are well-spaced, providing a balanced and organized layout. This change enhances the visual structure and makes it easier for users to interact with each button individually without feeling cluttered.

## Screenshots / Videos (if applicable)

Before modification:
Screenshot 2024-06-28 221004

After I modified:
Screenshot 2024-07-03 230642

### CODE REVIEW

**Comment by dhairyagothi** [comment]
good @Shivakumarjagadam give email id

**Review by dhairyagothi — APPROVED** [review]

**Comment by Shivakumarjagadam** [comment]
@dhairyagothi thank you
My email id: bablu4445550@gmail.com

**Comment by Shivakumarjagadam** [comment]
@dhairyagothi  Till now it was not merged,can you merge this please?

**Comment by Shivakumarjagadam** [comment]
@dhairyagothi  till now it was not merged ,can you  merge this please?

**Pull request merged**
