### PR TITLE
Movie Search engine 

### PR DESCRIPTION
**Pull request by MonishRaman**
## Related Issue: #130 

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
write issue no. here

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

check in issue by entering [X] in boxes

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have followed the code style guidelines of this project.
- [ ] I have checked for any existing open issues that my pull request may address.
- [ ] I have ensured that my changes do not break any existing functionality.
- [ ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ ] I have read the resources for guidance listed below.
- [ ] I have followed security best practices in my code changes.

check in issue by entering [X] in boxes
## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **Easy** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **Medium**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Easy:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Medium:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Hard:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
nahi chal rahi abhi bhi 
kuch api key h kya isme ??

**Comment by MonishRaman** [comment]
in other device also i tried its working

**Comment by MonishRaman** [comment]
don't know y its not working there

**Comment by MonishRaman** [comment]
i think bcz of that security error its showing

**Comment by MonishRaman** [comment]
yes there is a api key in js file

**Comment by dhairyagothi** [comment]
> yes there is a api key in js file

share ss of code where it is

**Comment by MonishRaman** [comment]
image

**Comment by dhairyagothi** [comment]
from where i can get api url ?

**Comment by dhairyagothi** [comment]
you have not added upi url that's why it is not working

**Comment by MonishRaman** [comment]
oh ok i will look over it and edit it

**Comment by dhairyagothi** [comment]
wait share me api website link

**Comment by MonishRaman** [comment]
https://developer.themoviedb.org/reference/intro/getting-started

**Comment by MonishRaman** [comment]
To get a TMDB (The Movie Database) API key, follow these steps:

Step 1: Create a TMDB Account
Go to the TMDB website: [TMDB](https://www.themoviedb.org/).
Click on "Login" in the top right corner. If you don't have an account, click on "Join TMDB" to create one.
Follow the instructions to sign up for an account.
Step 2: Verify Your Email
After signing up, you will receive a verification email. Follow the link in the email to verify your account.

Step 3: Request an API Key
Once your account is verified, log in to TMDB.
Click on your profile icon in the top right corner and select "Settings".
In the settings menu, click on "API" from the left sidebar.
Click on the "Create" button to request an API key.
Fill out the required information such as your application name, URL (if applicable), and a short description of your application.
Agree to the terms of use and click "Submit".
Step 4: Access Your API Key
After submitting the form, your API key will be generated and displayed in the "API" section of your account settings. You can now use this API key in your application to access TMDB's API.

**Comment by dhairyagothi** [comment]
@MonishRaman check your api key and base url once it is not valid i think

**Comment by MonishRaman** [comment]
ok let me check that

**Comment by MonishRaman** [comment]
i created new api

**Comment by MonishRaman** [comment]
91f41d3ef950816ce6f2445e7a81ddae
this is my api

**Comment by MonishRaman** [comment]
image

**Comment by dhairyagothi** [comment]
Still not working 
Let's merge it

**Comment by MonishRaman** [comment]
ok bro

**Pull request merged**
