### PR TITLE
Page loader aligned

### PR DESCRIPTION
**Pull request by deepak-d-r4113**
## Related Issue
Preloader alignment and size correction

Add issue no. #3

## Description
This pull request fixes the alignment and size of the preloader

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@deepak-d-r4113 first PULL the MAIN branch UI is changed and share a video of changes made

**Review by dhairyagothi — CHANGES_REQUESTED** [review]
PULL MAIN branch first

**Comment by dhairyagothi** [comment]
good @deepak-d-r4113

**Comment by deepak-d-r4113** [comment]
so its finished right?

**Comment by dhairyagothi** [comment]
> so its finished right?

Check score board you got 10 point

**Pull request merged**
