### PR TITLE
Feat : Added Stock profit calculator as a Day-72 Project 

### LINKED ISSUE #264: Feat : Adding a Stock profit Calculator as a project
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Want to add a stock profit calculator.
Using this user just have to give input of no. of shares , purchase price in INR , sell price , buy commision , sell commission then the calculator will display purchased for , sold for and profit amount to the user to analyze their overall stock activity and help them to further invest in stock market

**Describe alternatives you've considered**

**Additional context**

@dhairyagothi assign this to me , I am working under VSOC . Thanks

### PR DESCRIPTION
**Pull request by Meetjain1**
## Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
write issue no. here
closes #264 

## Email id used to regsiter for VSoc'24
meetofficialhere@gmail.com

### Stock Profit Calculator
The Stock Profit Calculator is a dynamic web application designed to help users analyze their stock transactions and make informed investment decisions. Built using HTML, CSS, and JavaScript, this tool provides a seamless and intuitive user experience with a beautiful user interface, smooth animations, and robust calculation functionality.

#### Key Features:
- **User-Friendly Interface**: The calculator boasts a clean and visually appealing interface that makes it easy to use for anyone.
- **Interactive Animations**: The application includes smooth animations and hover effects to enhance the user experience.
- **Real-Time Calculations**: Users can input data and receive instant calculations of their stock transactions.
- **Detailed Output**: The calculator displays the total amount spent on purchasing the shares, the total amount received from selling the shares, and the profit or loss incurred.
- **Responsiveness**: The application is fully responsive, ensuring a consistent experience across desktops, tablets, and mobile devices.
- **ReadMe File**: The project includes a comprehensive README file with instructions and details about the application.

#### How It Works:
1. **Input Fields**:
   - Number of Shares
   - Purchase Price (INR)
   - Sell Price (INR)
   - Buy Commission
   - Sell Commission
   - 
2. **Output**:
   - **Purchased For**: Total amount spent on purchasing the shares.
   - **Sold For**: Total amount received from selling the shares.
   - **Profit Amount**: The profit or loss incurred from the transaction.

#### User Interaction:
- Users simply need to fill in the input fields with the relevant data.
- Upon clicking the calculate button, the calculator will display the results in a well-organized and readable format.

#### Benefits:
- **Time-Saving**: Quickly analyze stock transactions without manual calculations.
- **Investment Insight**: Helps users to evaluate their stock activity and make better investment decisions.

This project is perfect for anyone looking to keep track of their stock investments and maximize their returns. With its modern design and efficient functionality, the Stock Profit Calculator is an essential tool for every investor.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

check in issue by entering [X] in boxes

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have followed the code style guidelines of this project.
- [X] I have checked for any existing open issues that my pull request may address.
- [X] I have ensured that my changes do not break any existing functionality.
- [] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X] I have read the resources for guidance listed below.
- [X] I have followed security best practices in my code changes.

check in issue by entering [X] in boxes
## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **Easy** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **Medium**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Easy:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Medium:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Hard:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
image

@Meetjain1 please reolve conflicts add as day 73

**Comment by Meetjain1** [comment]
@dhairyagothi I think I have to add as day 74 right ?
image

**Comment by Meetjain1** [comment]
@dhairyagothi resolved now check it

**Comment by Meetjain1** [comment]
@dhairyagothi any issues ?

**Comment by dhairyagothi** [comment]
no

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
