### PR TITLE
gave animation in ping pong game

### PR DESCRIPTION
**Pull request by Krishna100604**
@dhairyagothi merge this

### CODE REVIEW

**Comment by Krishna100604** [comment]
@merge this pr

**Comment by dhairyagothi** [comment]
@Krishna100604  DONT REMOVE PR FORMAT WHILE MAKING A PR GIVE EMAIL ID

**Comment by Krishna100604** [comment]
i guess both of PR handled in this @dhairyagothi

**Comment by Krishna100604** [comment]
> @Krishna100604 DONT REMOVE PR FORMAT WHILE MAKING A PR GIVE EMAIL ID

shrikrishnaprajapati106@gmail.com

**Comment by dhairyagothi** [comment]
wrong email id  @Krishna100604 contact me on discord

**Comment by Krishna100604** [comment]
> wrong email id @Krishna100604 contact me on discord

check discord

**Pull request merged**
