### PR TITLE
#294 Addition of login and sign up page

### PR DESCRIPTION
**Pull request by Aaryanb45**
made a new button for login and also created 2 page 
1 login page
2 singup pages
Also added images and transition property to look appealing
Screenshot 2024-07-16 at 1 22 34 PM
Screenshot 2024-07-16 at 1 22 41 PM
label:bonus

### CODE REVIEW

**Comment by Aaryanb45** [comment]
hey @dhairyagothi  can u pull it

**Comment by dhairyagothi** [comment]
email id ?? issue no ?? @Aaryanb45  do pr comment properly

**Comment by Aaryanb45** [comment]
issue no #294 
aryanbansal182004@gmail.com

**Review by dhairyagothi — APPROVED** [review]
can be improved

**Pull request merged**
