### PR TITLE
Movie Search App is done

### PR DESCRIPTION
**Pull request by MonishRaman**
## Related Issue #130 

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
write issue no. here

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

check in issue by entering [X] in boxes

## Screenshots / Videos (if applicable)

https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/65109127-70b1-4ed0-8f17-61810907bbd8

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [X ] I have performed a self-review of my code.
- [X ] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have followed the code style guidelines of this project.
- [ X] I have checked for any existing open issues that my pull request may address.
- [X ] I have ensured that my changes do not break any existing functionality.
- [X ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ X] I have read the resources for guidance listed below.
- [X ] I have followed security best practices in my code changes.

check in issue by entering [X] in boxes
## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **Easy** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **Medium**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Easy:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Medium:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Hard:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
image

solve it @MonishRaman

**Comment by MonishRaman** [comment]
done

**Comment by dhairyagothi** [comment]
image

what is this ??

**Comment by MonishRaman** [comment]
its me

**Comment by MonishRaman** [comment]
monish and my initial is r

**Comment by dhairyagothi** [comment]
Ek baar check kar na bhai nahi chal raha uska preview koi movie hi nahi show ho rahi h

**Comment by MonishRaman** [comment]
is it ok
let me check

**Comment by MonishRaman** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/c4f20d9d-46c3-4222-b2ad-36daddd51849

**Comment by MonishRaman** [comment]
check now

**Comment by dhairyagothi** [comment]
image
 do again

**Pull request closed without merging**
