### PR TITLE
Razorpay clone file push

### PR DESCRIPTION
**Pull request by bhagwan8815**
## Related Issue

Related issue : Project enhancement and  Documentation update.
Project name: Razorpay Clone
Issue number #162 

## Email id used to regsiter for VSoc'24
Email id : ranabhagwan8815@gmail.com

## Description
I am add a new project in your Repository which is RAZORPAY CLONE.  this is  a Payments solutions in india that allows business to accept, process and disburse payments with its products suite.

## Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ X] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

check in issue by entering [X] in boxes

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x ] I have performed a self-review of my code.
- [ x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have followed the code style guidelines of this project.
- [x ] I have checked for any existing open issues that my pull request may address.
- [ x] I have ensured that my changes do not break any existing functionality.
- [ x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ x] I have read the resources for guidance listed below.
- [ x
WhatsApp Image 2024-06-24 at 11 57 00_1fa7c458
] I have followed security best practices in my code changes.

check in issue by entering [X] in boxes
## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **Easy** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **Medium**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Easy:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Medium:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Hard:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!
WhatsApp Image 2024-06-24 at 11 57 00_1fa7c458
WhatsApp Image 2024-06-24 at 11 57 22_b1602304
WhatsApp Image 2024-06-24 at 11 57 37_518d6fbc

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@bhagwan8815 please provide a video of changes

**Comment by dhairyagothi** [comment]
@bhagwan8815 also update index.html file

**Comment by bhagwan8815** [comment]
https://github.com/dhairyagothi/50_days_50_web_project/assets/130534171/1923f2c7-bc77-4e3e-bc6e-9124fbbc1d7b

Please can you tell me what changes need to be made in the index.html file ?

**Comment by dhairyagothi** [comment]
merged @bhagwan8815

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
