### PR TITLE
updated by Shivakumar Jagadam

### PR DESCRIPTION
**Pull request by Shivakumarjagadam**
i modified css page and html page and also added a flame image in the TODOLIST.

Screenshot 2024-06-20 233415

This is updated by me.

Screenshot 2024-06-20 001809

This is the actual one and the above one is modified by me.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
image

do changes in new files 
PULL MAIN branch first

**Comment by dhairyagothi** [comment]
image

conflicts are there

**Comment by Shivakumarjagadam** [comment]
Its been a while since i checked again so, i will check and do further changes that are required.

**Comment by dhairyagothi** [comment]
Okay

**Comment by dhairyagothi** [comment]
make a new PR @Shivakumarjagadam

**Comment by Shivakumarjagadam** [comment]
Sure,I'll do it

**Pull request closed without merging**
