### PR TITLE
# 284 added nav searchbar and changed footer section

### PR DESCRIPTION
**Pull request by NavAneEth777**
## Navigation Section Enhancements:
1. Added a search bar to the navigation section.
2. Implemented a function that enables the search bar to search through projects.

## Footer Improvements:
1. Updated the styling of the footer.
2. Made the footer fixed at the bottom of the website.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
which issue u are working @NavAneEth777 ??

**Comment by NavAneEth777** [comment]
> which issue u are working @NavAneEth777 ??

1. Search Functionality: I added a search bar that allows you to search through all 76 projects. You can now type in the name of any project, and it will show the relevant results.
2. Footer Adjustment: The footer was previously not fixed to the bottom of the page. I’ve fixed it so it now stays at the bottom."

**Comment by dhairyagothi** [comment]
You have not assigned any issue @NavAneEth777 

Make an issue first

**Comment by dhairyagothi** [comment]
@NavAneEth777 there are conflicts

**Pull request closed without merging**
