### PR TITLE
All the Works are completed

### PR DESCRIPTION
**Pull request by MonishRaman**
## Related Issues: #104 #72 #82 

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
write issue no. here

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ X] Feature enhancement
- [x] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

check in issue by entering [X] in boxes

## Screenshots / Videos (if applicable)

https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/212b3c7d-897c-403d-bcf8-75893d889f00

https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/525eaadf-7988-4dc7-8b5e-795eec14dccc

https://github.com/dhairyagothi/50_days_50_web_project/assets/140420819/8d8dc67c-fdb3-4d2c-90a4-7247d184211f

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [X ] I have performed a self-review of my code.
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have followed the code style guidelines of this project.
- [ X] I have checked for any existing open issues that my pull request may address.
- [X ] I have ensured that my changes do not break any existing functionality.
- [X ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ X] I have read the resources for guidance listed below.
- [ X] I have followed security best practices in my code changes.

check in issue by entering [X] in boxes
## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **Easy** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **Medium**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Easy:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Medium:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Hard:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
image

how to play this add some details confusing

**Comment by dhairyagothi** [comment]
image

already told you to not change complete code
want same html css

**Comment by MonishRaman** [comment]
Black Jack Game:-

It is a classic casino game "Black Jack". I've used HTML, CSS and Javascript for this project. Also I've added some sound effect to make game interesting.

Rules -
Game Rules Blackjack is a popular card game that is simple to play. The object of the game is to beat the dealer in one of the following ways:

• Get 21 points on the player's first two cards (called a "blackjack" or "natural") without a dealer blackjack;

• Reach a final score higher than the dealer without exceeding 21

• Let the dealer draw additional cards until their hand exceeds 21 ("busted").

image

**Let's Play**

image

(You Win)

image

(You Lose)

image

**Comment by dhairyagothi** [comment]
change snake game i want same UI

**Comment by dhairyagothi** [comment]
Don't copy paste code from somewhere

I will not merge if same thing occurs

**Pull request merged**
