### PR TITLE
added new UI to homepage , added search feature

### PR DESCRIPTION
**Pull request by raunaksingh9800**
## Related Issue

Changing UI of website #33

## Description

- added the UI as per the video 
- Filled Up the Project List now its not random data
- Added Search Feature 
- Added the glow card on search
- all other projects not effected 

## Type of PR

- [ ] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

check in issue by entering [X] in boxes

## Screenshots / Videos (if applicable)

https://drive.google.com/file/d/1dqJnZ7BFMszBgIn1CY0PhCZQjc2lkB-l/view?usp=sharing

## Checklist
- [X] I have performed a self-review of my code.
- [X ] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have followed the code style guidelines of this project.
- [ X] I have checked for any existing open issues that my pull request may address.
- [ X] I have ensured that my changes do not break any existing functionality.
- [ X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X ] I have read the resources for guidance listed below.
- [ X] I have followed security best practices in my code changes.

check in issue by entering [X] in boxes
## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **Easy** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **Medium**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Easy:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Medium:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Hard:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
GOOD JOB @raunaksingh9800 THANKU FOR YOUR CONTRIBUTION

**Comment by dhairyagothi** [comment]
@raunaksingh9800  EMAIL ID

**Comment by raunaksingh9800** [comment]
@dhairyagothi  welcome bro its all about helping each other

my email ID is raunaksingh9800@gmail.com

lets hope to stay in touch

**Comment by dhairyagothi** [comment]
image
 please resolve this @raunaksingh9800

**Comment by raunaksingh9800** [comment]
@dhairyagothi  you don't need to do anything . just go to home.js there you have a JS object add projects to that
its in the format
`<day : int>  : {
 title : string
 ..... and so on
}
`
the index.html is now just a template file

Because for the search feature to work and render DOM to append correct info into the index.html it needs to use the 
js object

**Pull request closed without merging**
