### PR TITLE
Added Cricket Game

### PR DESCRIPTION
**Pull request by Shivakumarjagadam**
i added cricket_game as  a Day-54 with demo link @dhairyagothi 

under VSOC24

Screenshot 2024-06-23 002944

### CODE REVIEW

**Review by dhairyagothi — CHANGES_REQUESTED** [review]
where is folder files ??
image

fix it

**Comment by Shivakumarjagadam** [comment]
ok i added but due to some glitch it is not added properly

**Comment by Shivakumarjagadam** [comment]
Check again i added the folder with files.

**Review by Shivakumarjagadam — COMMENTED** [review]
Ok im unable to fix this,shall I delete this and do once again

**Comment by Shivakumarjagadam** [comment]
Its was unable to fix,can i deletd this fork and do once again

**Pull request closed without merging**
