### PR TITLE
Missionaries and Cannibals game

### PR DESCRIPTION
**Pull request by AnantAgarwaL11**
Missionaries and Cannibals game 
Screenshot 2024-06-17 220446
Screenshot 2024-06-17 220425

### CODE REVIEW

**Comment by dhairyagothi** [comment]
good @AnantAgarwaL11  just add a instruction regarding how to play the game its bit confusing

**Comment by AnantAgarwaL11** [comment]
ok I'll do it

**Comment by AnantAgarwaL11** [comment]
Is it Okay now ??
Screenshot 2024-06-18 110621

**Review by AnantAgarwaL11 — COMMENTED** [review]
Just added the instructions to play the game

**Comment by dhairyagothi** [comment]
bro the UI has changed you first PULL the main branch Index.html file has changed
image

**Pull request closed without merging**
