### PR TITLE
Page loader aligned

### PR DESCRIPTION
**Pull request by deepak-d-r4113**
## Related Issue
Preloader alignment and size correction

Add issue no. #3

## Description
This pull request fixes the alignment and size of the preloader

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@deepak-d-r4113 please share a video of changes 


Uploading Recording 2024-06-18 152257.mp4…

not changed

**Review by dhairyagothi — CHANGES_REQUESTED** [review]
no changes in file

**Comment by dhairyagothi** [comment]
@deepak-d-r4113 change page loader of main page

**Comment by dhairyagothi** [comment]
@deepak-d-r4113 make changes fast

**Comment by deepak-d-r4113** [comment]
Hey i am kind of confused rright now should i do the page loader for
Screenshot 2024-06-18 184450
or inside the page loader project

**Comment by deepak-d-r4113** [comment]
its my first time contributing its kind of confusing me

**Comment by dhairyagothi** [comment]
@deepak-d-r4113 merge previous PR got 10 points for that closing this one

**Pull request closed without merging**
