### PR TITLE
Upgrading Vanilla JavaScript Calculator to Include Scientific Functions

### PR DESCRIPTION
**Pull request by atharva012004**
Related Issue
Upgrading Vanilla JavaScript Calculator to Include Scientific Functions

Description
This pull request proposes upgrading the Vanilla JavaScript Calculator Master to include scientific calculator features. These features will enable users to perform complex mathematical operations beyond basic arithmetic, including:

Trigonometric functions (sin, cos, tan, etc.)
Logarithmic calculations (log, ln)
Exponentials
And potentially more

Type of PR
-[X] Feature enhancement

## Screenshots / Videos (if applicable)

https://github.com/dhairyagothi/50_days_50_web_project/assets/136626840/d6b645ea-016f-4713-b5b1-da8df8fd0643

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have followed the code style guidelines of this project.
- [X] I have checked for any existing open issues that my pull request may address.
- [X] I have ensured that my changes do not break any existing functionality.
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X] I have read the resources for guidance listed below.
- [X] I have followed security best practices in my code changes.

Additional Context
This upgrade aims to transform the Vanilla JavaScript Calculator Master into a comprehensive tool for a wider range of users, particularly those in technical fields requiring advanced mathematical calculations. It aligns with user feedback and industry trends towards more robust calculator functionalities. We believe this enhancement will significantly improve user satisfaction and broaden the application's utility.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
image

make this button large and add scientific on button

**Comment by atharva012004** [comment]
Ok that button i will fix but what do you mean by scientific on button can you explain pls so that I'll work on it

**Comment by atharva012004** [comment]
brought button on display screen to make it easily accessible for user
Screenshot 2024-06-24 003004
Screenshot 2024-06-24 003017

**Comment by atharva012004** [comment]
Update is done and everything works perfectly so you can merge it now in the main branch

**Comment by dhairyagothi** [comment]
okay good @atharva012004

**Comment by dhairyagothi** [comment]
email id @atharva012004

**Review by dhairyagothi — APPROVED** [review]

**Comment by atharva012004** [comment]
Final update is done all the functions are working correctly i have dry run the code once again and also changes the scientific toggle button img which looks more decent now actually it take lots of effort to make changes in the script you can see the changes so please i wanna request you to mark It hard and you can now merge it to main branch now.

Email id - atharavashihurkar@gmail.com

Screenshot 2024-06-24 130305
Screenshot 2024-06-24 130315

**Pull request merged**
